import type { NextPage } from "next";
import Head from "next/head";
import { PostCard, Categories, PostWidget } from "../components";

const posts = [
  {
    title: "react testing",
    excerpt:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptate amet sit eius porro rem labore illum rerum aliquid voluptatum perspiciatis ipsam, qui iusto aut et, nulla expedita eos dicta. Fugit.",
  },
  {
    title: "react testing",
    excerpt:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptate amet sit eius porro rem labore illum rerum aliquid voluptatum perspiciatis ipsam, qui iusto aut et, nulla expedita eos dicta. Fugit.",
  },
];

const Home: NextPage = () => {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>CMS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post, index) => {
            return <PostCard post={post} key={index} />;
          })}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8 ">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
